### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 888

### ISSUE THREAD

**Issue by yxkyong** [junwei-wang/cpabe#10]
I installed the cpabe(The paper ''Ciphertext-Policy Attribute-Based Encryption " provide) in Linux. I want to use your decode function in Java. I use ther pub_key, private_key and encode.pdf.cpabe  generated by the Linux cpabe function. When I use your decode function to decode the encode.pdf.cpabe:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 888
	at bswabe.SerializeUtils.unserializeString(SerializeUtils.java:61)
	at bswabe.SerializeUtils.unserializeBswabePub(SerializeUtils.java:87)
	at cpabe.Cpabe.dec(Cpabe.java:109)
	at DemoForCpabe.main(DemoForCpabe.java:434)
Could you please tell me what cause this? I tried, but I couldn't find a solution.

**Comment by yxkyong** [comment]
whether the format of your file is different from the Linux one?

**Comment by junwei-wang** [comment]
Yes, the incompatibility between these two works.

**Comment by yxkyong** [comment]
May I ask you a question ? You said "setup is the process of initilize public parameters and master key, "pubfile" is your public file and "mskfile" is the path for your master key file." If I don't have a pub_key, how to generate one with your code?

**Comment by junwei-wang** [comment]
Please read this file /src/DemoForCpabe.java

**Comment by junwei-wang** [comment]
I have moved the project to build by Maven. 
The dependency problem will be automatically solved.
Checkout [BUILD.md]
