### ISSUE TITLE
imports cannot be resolved.

### ISSUE THREAD

**Issue by bjambu20** [junwei-wang/cpabe#5]
below imports cannot be resolved:
Even i have jar file cpabe 2.0.0 and if i use cpabe 1.2.1 i get err.
1. it.unisa.dia.gas.jpbc.CurveParameters and 
2. it.unisa.dia.gas.plaf.jpbc.pairing.DefaultCurveParameters

Anyone help me to solve this pbm.

**Comment by RANJANIRAMALINGAMM** [comment]
Even using jpbc am geeting error

**Comment by RANJANIRAMALINGAMM** [comment]
How should we give  access policy input to cpabe..kindly help me...am completely  new to this type of cryptography

**Comment by junwei-wang** [comment]
Please have a look of this link http://junwei-wang.github.io/cpabe/

**Comment by RANJANIRAMALINGAMM** [comment]
Thank you sir..
   I have included all the 9 jars in jpbc...but the imports is not resolved for  "it.unisa.dia.gas.plaf.jpbc.pairing.DefaultCurveParameters " alone sir...now what should i do for this ?...kindly help me sir

**Comment by RANJANIRAMALINGAMM** [comment]
I have tried cpabe given on your site.but that only import can't be resolved eventhough i have included all the necessary jpbc jars..kindly help me sir

**Comment by RANJANIRAMALINGAMM** [comment]
Sir You are my only hope to solve this problem..i have attached a snapshot of where i am getting error...kindly help me sir...
![doubt](https://cloud.githubusercontent.com/assets/10693306/6365450/f7c3dab6-bcdd-11e4-86e3-d305d7ddf547.png)

**Comment by RANJANIRAMALINGAMM** [comment]
SIr i have resolved that import..but in your code you are using curveparameters for getpairing() function ...i have attached the code...
DefaultCurveParameters params = new DefaultCurveParameters()
				.load(new ByteArrayInputStream(curveParams.getBytes()));

	
                pairing = PairingFactory.getPairing(params);
here actually pairingparameters or string only we can pass for getpairing function..how to convert default curveparameters into pairingparameter..

**Comment by RANJANIRAMALINGAMM** [comment]
Sir kindly help me...I am stucking here...how to pass value to getpairing function

**Comment by RANJANIRAMALINGAMM** [comment]
How to check jpbc wrapper is correctly installed

**Comment by junwei-wang** [comment]
Sorry @RANJANIRAMALINGAMM , Please refer to the manual of your IDE about how to import an library.

**Comment by bjambu20** [comment]
@RANJANIRAMALINGAMM . I was able to run . So you may try another project in netbeans with appropriate jars. Otherwise try in eclipse.. Sure it will work..

**Comment by RANJANIRAMALINGAMM** [comment]
thank you sir ...whether i need to install PBC

**Comment by RANJANIRAMALINGAMM** [comment]
i have installed jpbc library and run a small program for checking..it executes successfully...Whether i need to install pbc for this Cpabe code to run...can you please reply me

**Comment by junwei-wang** [comment]
@RANJANIRAMALINGAMM , you do not have to install `pbc` on you compute, but you have to download `jPBC`, and add it into the search PATH.

**Comment by chenlog** [comment]
maybe there is path problem, you try use file wheathe it can open the
property

2015-03-18 15:27 GMT+08:00 Junwei Wang <notifications@github.com>:

> @RANJANIRAMALINGAMM <https://github.com/RANJANIRAMALINGAMM> , you do not
> have to install pbc on you compute, but you have to download jPBC, and
> add it into the search PATH.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/junwei-wang/cpabe/issues/5#issuecomment-82791239>.
>



-- 
感谢您拔冗阅读此邮件
此致
敬礼

**Comment by RANJANIRAMALINGAMM** [comment]
Thank you very much sir...i have downloaded jpbc and included all the 13 jars in netbeans...I am not getting any error...but while running the program i got the below errors...the encrypted file also cant open normally...but decrypted file could be open...
![doubtt](https://cloud.githubusercontent.com/assets/10693306/6727464/181aea9a-ce48-11e4-8a3e-a34c0a249cf7.png)

**Comment by RANJANIRAMALINGAMM** [comment]
How should i rectify this problem...why jpbc-pbc library module is not found eventhough i installed all the neccessary jars..
                 pairing = PairingFactory.getPairing(params); 
I am getting runtime error in the above statement when i run your code given in your site...how to solve this??kindly help me sir.

**Comment by helpzht** [comment]
Just remove the jpbc-pbc-1.2.0.jar from your project, and you will see nothing serious happen with your project. but, the link error will disappear.

**Comment by mangesh0910** [comment]
Sir,
    i am new to this approch....i have already added all jars...
    i am facing same problem as ranjaniramalingamm mention above
    getting compiletime error on following
    pairing=PairingFactory.getPairing(params);
   Sir plz kindly tell me proceess to resolve mentioned error..

**Comment by junwei-wang** [comment]
@mangesh0910 Did you use the correct version of jPBC?

**Comment by mangesh0910** [comment]
try jpbc 2.0.0 as well as jpbc 1.2.1 still getting same error sir..,,

**Comment by junwei-wang** [comment]
Please read the source code and find out the reason. I don't maintain this
project any more. I am sorry.

2015-05-12 12:56 GMT+08:00 mangesh0910 <notifications@github.com>:

**Comment by meetalisaxena** [comment]
hello sir, is there any one who can guide on me in the same above error ?

**Comment by hassanel** [comment]
Hello Mr. @junwei-wang , I tried to execute the main class **DemoForCpabe.class** but I've got this error exception : 
![capture](https://user-images.githubusercontent.com/10168372/27996360-548d4fee-64d8-11e7-9f23-ffab36114c26.PNG)

**Comment by junwei-wang** [comment]
Duplicated and closed issue #6.

**Comment by knagaraju799** [comment]
@RANJANIRAMALINGAMM  did u solve that error ?? now .. I am getting the same error which u got for curveparams .. please help me out.
